### ISSUE TITLE
Program gets killed on Mac M1

### ISSUE THREAD

**Issue by YamashitaRen** [panmau/switchtube-dl#3] opened 2022-02-27 15:18 UTC
**Information**
 - OS: MacOS M1
 - Version: 0.0.5
 - Terminal: Mac

The program does not seem to work on Mac M1. I installed it with homebrew.
`% switchtube-dl --help`
`zsh: killed     switchtube-dl`

**Comment by panmau** [comment] 2022-02-27 23:46
Thanks for the interest in the tool and reporting this. ARM is the only platform I haven't tested yet.

What happens if you just execute 'switchtube-dl' as is?
If you have the same error: Can you try downloading the latest ARM build, extract the gzip and execute the binary from the directory you downloaded it to? Does it have the same behavior?

This way I can find out if something is wrong with --version, the Formula or maybe with the ARM packaging itself.

**Comment by iamfabio** [comment] 2022-02-28 12:22
I am having the same issue on my M1 Mac. I've tried your troubleshooting steps and it seems that the software does not have a verified developer. If I remember correctly, you'd need to boot in recovery mode to execute unverified programs (there's a setting that lets you get around this there). I have attached a screenshot of the error I am getting:
<img width="572" alt="Screenshot 2022-02-28 at 13 18 40" src="https://user-images.githubusercontent.com/30632870/155982724-719b5a8f-7af9-414d-be74-fe708a2c24cb.png">

Hope this helps. Thanks for the tool!

**Comment by YamashitaRen** [comment] 2022-02-28 18:16
@panmau It is rather me, who should thank you for switchtube-dl :)

I just tested the github archive, same issue. I am a noob at Mac unfortunately so I can't do much more...

@iamfabio 
When this happens, you need to go in "Security" and allow the app.

**Comment by panmau** [comment] 2022-02-28 19:16
Thanks for the initial troubleshooting. It seems to be not related to the unverified software.

It could be that one of my dependencies doesn't yet support the M1 chip, which I'm currently investigating. It is a bit difficult though without actual access to such a machine. I will try to find someone in RL that has one so that I can find the root cause for it.

**Comment by panmau** [comment] 2022-02-28 21:26
Can you check whether you can find a crash report in the `Console` app after executing switchtube-dl?
This should hopefully output a more detailed error message.

**Comment by YamashitaRen** [comment] 2022-02-28 21:37
It does not look like there is any unfortunately...

**Comment by panmau** [comment] 2022-02-28 23:02
@YamashitaRen @iamfabio I published a potential fix as a [prerelease](https://github.com/panmau/switchtube-dl/releases/tag/0.0.6). It is also available via homebrew.

Can you try whether this solves your issue?

**Comment by YamashitaRen** [comment] 2022-02-28 23:05
It works \o/

**Comment by iamfabio** [comment] 2022-02-28 23:23
Wow, that was some quick bug fixing. Thank you very much, I appreciate your work! Everything seems to work perfectly now 👍

**Comment by panmau** [comment] 2022-02-28 23:39
I'm very glad that this works now! If you're interested in the why it works, I wrote some details in the PR.

Thanks again for reporting and troubleshooting it.
I will close this issue now.

**Closed by panmau** 2022-02-28 23:39 UTC
Labels: category: bug
